FROM python:3.11

WORKDIR /project

ADD backend /project/backend
ADD requirements.txt /project/requirements.txt

RUN pip install -r requirements.txt

CMD ["fastapi", "dev","--host","0.0.0.0", "backend/app.py"]

EXPOSE 8000